server:
  port: ${TLS_PORT:443}
  config-server:
    port: ${CONFIG_SERVER_PORT:8080}
  main-server:
    port: ${PORT:80}
    io-select-count: ${MAIN_SERVER_IO_SELECT_COUNT:1}
    io-work-count: ${MAIN_SERVER_IO_WORK_COUNT:0}
  http2:
    enabled: ${HTTP_2_ENABLED:false}
  ssl:
    enabled: false

spring:
  application:
    name: ${APP_NAME:great-wall}
  messages:
    basename: i18n/message
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true
  jackson:
    # 解决 jackson @JsonFormat 序列化时差
    time-zone: GMT+8
    serialization:
      # 将时间转为时间戳输出
      write-dates-as-timestamps: true
      write-null-map-values: true
      write-empty-json-arrays: true
    default-property-inclusion: non_null
  threads:
    virtual:
      enabled: ${VIRTUAL_THREAD:false}
  cloud:
    gateway:
      # 开启过滤器缓存
      route-filter-cache-enabled: true
      httpclient:
        ssl:
          # 是否信任所有证书
          use-insecure-trust-manager: ${HTTPCLIENT_SSL_USE_INSECURE_TRUST_MANAGER:false}
        # 请求链接超时时间
        connect-timeout: ${HTTPCLIENT_CONNECT_TIMEOUT:3000}
        websocket:
          # 设置 ws 最大帧数字节长度
          max-frame-payload-length: ${WEBSOCKET_MAX_FRAME_PAYLOAD_LENGTH:6553500}
        # 代理请求连接池
        pool:
          type: elastic
          name: great-wall-proxy
          max-idle-time: ${HTTPCLIENT_POOL_MAX_IDLE_TIME:PT1S}
          max-life-time: ${HTTPCLIENT_POOL_MAX_LIFE_TIME:10H}
          eviction-interval: ${HTTPCLIENT_POOL_EVICTION_INTERVAL:10S}
      predicate:
        host:
          # host 匹配不导入端口
          include-port: false
  # r2dbc 配置
  r2dbc:
    url: file:${H2_FILE_DIR:./data/db}/db;MODE=MYSQL
    username: ${H2_USER:faLhBysh}
    password: ${H2_PASS:aclmUe6#!aq1tb0VL}
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
      validation-query: select 1
  # 初始化sql
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:sql/schema.sql
      encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/

site:
  tls:
    provider:
      # 基于来此加密的tls证书提供着
      osfipin:
        base-url: https://api.xwamp.com/
  auth:
    admin:
      password: ${ADMIN_PASSWORD:123456789}

logging:
  level:
    # 忽略只读告警
    "io.r2dbc.h2.H2Connection": error
    "cc.shacocloud.greatwall.controller.advice.RestfulResponseSpecification": info
    "org.springframework.cloud.gateway.handler": debug
#    "org.springframework.r2dbc.core.DefaultDatabaseClient": debug