server:
  port: 443
  config-server:
    port: 8080
  main-server:
    port: 80
    redirect-https: true
  http2:
    enabled: true
  ssl:
    enabled: false

spring:
  jackson:
    # 解决 jackson @JsonFormat 序列化时差
    time-zone: GMT+8
    serialization:
      # 将时间转为时间戳输出
      write-dates-as-timestamps: true
      write-null-map-values: true
      write-empty-json-arrays: true
    default-property-inclusion: non_null
  threads:
    virtual:
      enabled: false
  cloud:
    gateway:
      httpclient:
        websocket:
          # 设置 ws 最大帧数字节长度
          max-frame-payload-length: ${WEBSOCKET_MAX_FRAME_PAYLOAD_LENGTH:6553500}
        connect-timeout: ${HTTPCLIENT_CONNECT_TIMEOUT:3000}
        response-timeout: ${HTTPCLIENT_RESPONSE_TIMEOUT:10S}
        # 代理请求连接池
        pool:
          type: ELASTIC
          name: great-wall-proxy
          max-idle-time: ${HTTPCLIENT_POOL_MAX_IDLE_TIME:60S}
          max-life-time: ${HTTPCLIENT_POOL_MAX_LIFE_TIME:10H}
          eviction-interval: ${HTTPCLIENT_POOL_EVICTION_INTERVAL:10S}
  # r2dbc 配置
  r2dbc:
    url: file:${H2_FILE_DIR:./data/db}/db;MODE=MYSQL
    username: ${H2_USER:faLhBysh}
    password: ${H2_PASS:aclmUe6#!aq1tb0VL}
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
      validation-query: select 1
  # 初始化sql
  sql:
    init:
      mode: always
      schema-locations:
        - classpath*:sql/schema.sql
      encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/


site:
  tls:
    provider:
      # 基于来此加密的tls证书提供着
      osfipin:
        base-url: https://api.osfipin.com/letsencrypt/api
        token: f9c22e612cc15056fdc3c7c902b5882e
        user: 1679924785@qq.com
        auto-id: 5r8r9e
        domain: "*.shacocloud.cc"
  auth:
    admin:
      password: ${ADMIN_PASSWORD:123456789}

logging:
  level:
    root: info
    # 忽略只读告警
    "io.r2dbc.h2.H2Connection": error
#    "org.springframework.r2dbc.core.DefaultDatabaseClient": debug