
spring:
  threads:
    virtual:
      # 虚拟线程开启后将导致web server重启后关闭
      enabled: false
  cloud:
    gateway:
      # 路由配置
      routes:
        - id: true-nas
          uri: ${TRUE_NAS_ADDRESS:http://192.168.1.145:80}
          predicates:
            - Path=/test1