services:
  great-wall:
    image: moailaozi/great-wall:2.28
    container_name: great-wall
    environment:
      ADMIN_PASSWORD: moYgwfjHQD8RbQqG
    volumes:
      - /data/great-wall/data:/workspace/data
    network_mode: host

