name: CI Build and Deploy

on: workflow_dispatch

#on:
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

env:
  IMAGE_TAG: ${{ github.sha }}
  GITHUB_CI: -DGITHUB_CI=true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from build.gradle.kts
        id: version
        run: |
          echo "version=$(grep -Eo 'version\s*=\s*"[^"]+"' ./great-wall-server/build.gradle.kts | cut -d'"' -f2)" >> $GITHUB_ENV
          echo "IMAGE_TAG=$version" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          echo "::group::Building Docker images, IMAGE_TAG: $IMAGE_TAG"
          docker buildx bake -f docker-bake.hcl great-wall-bootJar --push --print
          docker buildx bake -f docker-bake.hcl great-wall --push --print
          docker buildx bake -f docker-bake.hcl great-wall-g1gc --push --print
          echo "::endgroup::"

      - name: Success message
        run: echo "::notice::========== 全部构建成功 =========="