name: CI Build and Deploy

on: workflow_dispatch

#on:
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

env:
  GITHUB_CI: -DGITHUB_CI=true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Restore Build Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker images
        uses: docker/bake-action@v4
        env:
          IMAGE_TAG: $(grep -Eo 'version\s*=\s*"[^"]+"' ./great-wall-server/build.gradle.kts | cut -d'"' -f2)
        with:
          files: docker-bake.hcl
          push: true
          targets: great-wall-bootJar,great-wall,great-wall-g1gc
          set: |
            *.tags=your-docker-hub-username/your-image:${IMAGE_TAG}
            *.cache-from=type=local,src=${{ github.workspace }}/.buildx-cache
            *.cache-to=type=local,dest=${{ github.workspace }}/.buildx-cache-new,mode=max

      - name: Update Cache Storage
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Success message
        run: echo "::notice::========== 全部构建成功 =========="